import type { Exchange } from "@tickerapp/shared";

export const GLOBAL_EXCHANGES: Exchange[] = [
  {
    id: "nasdaq",
    name: "NASDAQ",
    countryCode: "US",
    region: "north-america",
    currency: "USD",
    timezone: "America/New_York",
    regularSession: {
      open: "09:30",
      close: "16:00",
    },
  },
  {
    id: "nyse",
    name: "New York Stock Exchange",
    countryCode: "US",
    region: "north-america",
    currency: "USD",
    timezone: "America/New_York",
    regularSession: {
      open: "09:30",
      close: "16:00",
    },
  },
  {
    id: "tsx",
    name: "Toronto Stock Exchange",
    countryCode: "CA",
    region: "north-america",
    currency: "CAD",
    timezone: "America/Toronto",
    regularSession: {
      open: "09:30",
      close: "16:00",
    },
  },
  {
    id: "lse",
    name: "London Stock Exchange",
    countryCode: "GB",
    region: "europe",
    currency: "GBP",
    timezone: "Europe/London",
    regularSession: {
      open: "08:00",
      close: "16:30",
    },
  },
  {
    id: "xetra",
    name: "Xetra",
    countryCode: "DE",
    region: "europe",
    currency: "EUR",
    timezone: "Europe/Berlin",
    regularSession: {
      open: "09:00",
      close: "17:30",
    },
  },
  {
    id: "euronext-paris",
    name: "Euronext Paris",
    countryCode: "FR",
    region: "europe",
    currency: "EUR",
    timezone: "Europe/Paris",
    regularSession: {
      open: "09:00",
      close: "17:30",
    },
  },
  {
    id: "euronext-amsterdam",
    name: "Euronext Amsterdam",
    countryCode: "NL",
    region: "europe",
    currency: "EUR",
    timezone: "Europe/Amsterdam",
    regularSession: {
      open: "09:00",
      close: "17:30",
    },
  },
  {
    id: "six",
    name: "SIX Swiss Exchange",
    countryCode: "CH",
    region: "europe",
    currency: "CHF",
    timezone: "Europe/Zurich",
    regularSession: {
      open: "09:00",
      close: "17:30",
    },
  },
  {
    id: "nse",
    name: "National Stock Exchange of India",
    countryCode: "IN",
    region: "asia-pacific",
    currency: "INR",
    timezone: "Asia/Kolkata",
    regularSession: {
      open: "09:15",
      close: "15:30",
    },
  },
  {
    id: "jpx",
    name: "Japan Exchange Group",
    countryCode: "JP",
    region: "asia-pacific",
    currency: "JPY",
    timezone: "Asia/Tokyo",
    regularSession: {
      open: "09:00",
      close: "15:30",
    },
  },
  {
    id: "hkex",
    name: "Hong Kong Exchanges and Clearing",
    countryCode: "HK",
    region: "asia-pacific",
    currency: "HKD",
    timezone: "Asia/Hong_Kong",
    regularSession: {
      open: "09:30",
      close: "16:00",
    },
  },
  {
    id: "sse",
    name: "Shanghai Stock Exchange",
    countryCode: "CN",
    region: "asia-pacific",
    currency: "CNY",
    timezone: "Asia/Shanghai",
    regularSession: {
      open: "09:30",
      close: "15:00",
    },
  },
  {
    id: "szse",
    name: "Shenzhen Stock Exchange",
    countryCode: "CN",
    region: "asia-pacific",
    currency: "CNY",
    timezone: "Asia/Shanghai",
    regularSession: {
      open: "09:30",
      close: "15:00",
    },
  },
  {
    id: "krx",
    name: "Korea Exchange",
    countryCode: "KR",
    region: "asia-pacific",
    currency: "KRW",
    timezone: "Asia/Seoul",
    regularSession: {
      open: "09:00",
      close: "15:30",
    },
  },
  {
    id: "twse",
    name: "Taiwan Stock Exchange",
    countryCode: "TW",
    region: "asia-pacific",
    currency: "TWD",
    timezone: "Asia/Taipei",
    regularSession: {
      open: "09:00",
      close: "13:30",
    },
  },
  {
    id: "sgx",
    name: "Singapore Exchange",
    countryCode: "SG",
    region: "asia-pacific",
    currency: "SGD",
    timezone: "Asia/Singapore",
    regularSession: {
      open: "09:00",
      close: "17:00",
    },
  },
  {
    id: "asx",
    name: "Australian Securities Exchange",
    countryCode: "AU",
    region: "asia-pacific",
    currency: "AUD",
    timezone: "Australia/Sydney",
    regularSession: {
      open: "10:00",
      close: "16:00",
    },
  },
  {
    id: "b3",
    name: "B3",
    countryCode: "BR",
    region: "latin-america",
    currency: "BRL",
    timezone: "America/Sao_Paulo",
    regularSession: {
      open: "10:00",
      close: "17:00",
    },
  },
  {
    id: "bmv",
    name: "Mexican Stock Exchange",
    countryCode: "MX",
    region: "latin-america",
    currency: "MXN",
    timezone: "America/Mexico_City",
    regularSession: {
      open: "08:30",
      close: "15:00",
    },
  },
  {
    id: "jse",
    name: "Johannesburg Stock Exchange",
    countryCode: "ZA",
    region: "africa",
    currency: "ZAR",
    timezone: "Africa/Johannesburg",
    regularSession: {
      open: "09:00",
      close: "17:00",
    },
  },
];