import type { Instrument } from "@tickerapp/shared";

export const GLOBAL_INSTRUMENTS: Instrument[] = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    exchangeId: "nasdaq",
    countryCode: "US",
    currency: "USD",
    assetClass: "equity",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    exchangeId: "nasdaq",
    countryCode: "US",
    currency: "USD",
    assetClass: "equity",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    exchangeId: "nasdaq",
    countryCode: "US",
    currency: "USD",
    assetClass: "equity",
  },
  {
    symbol: "SHOP",
    name: "Shopify Inc.",
    exchangeId: "tsx",
    countryCode: "CA",
    currency: "CAD",
    assetClass: "equity",
  },
  {
    symbol: "SHEL",
    name: "Shell plc",
    exchangeId: "lse",
    countryCode: "GB",
    currency: "GBP",
    assetClass: "equity",
  },
  {
    symbol: "SAP",
    name: "SAP SE",
    exchangeId: "xetra",
    countryCode: "DE",
    currency: "EUR",
    assetClass: "equity",
  },
  {
    symbol: "MC",
    name: "LVMH Moet Hennessy Louis Vuitton SE",
    exchangeId: "euronext-paris",
    countryCode: "FR",
    currency: "EUR",
    assetClass: "equity",
  },
  {
    symbol: "ASML",
    name: "ASML Holding N.V.",
    exchangeId: "euronext-amsterdam",
    countryCode: "NL",
    currency: "EUR",
    assetClass: "equity",
  },
  {
    symbol: "NESN",
    name: "Nestle S.A.",
    exchangeId: "six",
    countryCode: "CH",
    currency: "CHF",
    assetClass: "equity",
  },
  {
    symbol: "RELIANCE",
    name: "Reliance Industries Limited",
    exchangeId: "nse",
    countryCode: "IN",
    currency: "INR",
    assetClass: "equity",
  },
  {
    symbol: "7203",
    name: "Toyota Motor Corporation",
    exchangeId: "jpx",
    countryCode: "JP",
    currency: "JPY",
    assetClass: "equity",
  },
  {
    symbol: "0700",
    name: "Tencent Holdings Limited",
    exchangeId: "hkex",
    countryCode: "HK",
    currency: "HKD",
    assetClass: "equity",
  },
  {
    symbol: "600519",
    name: "Kweichow Moutai Co., Ltd.",
    exchangeId: "sse",
    countryCode: "CN",
    currency: "CNY",
    assetClass: "equity",
  },
  {
    symbol: "000001",
    name: "Ping An Bank Co., Ltd.",
    exchangeId: "szse",
    countryCode: "CN",
    currency: "CNY",
    assetClass: "equity",
  },
  {
    symbol: "005930",
    name: "Samsung Electronics Co., Ltd.",
    exchangeId: "krx",
    countryCode: "KR",
    currency: "KRW",
    assetClass: "equity",
  },
  {
    symbol: "2330",
    name: "Taiwan Semiconductor Manufacturing Company Limited",
    exchangeId: "twse",
    countryCode: "TW",
    currency: "TWD",
    assetClass: "equity",
  },
  {
    symbol: "D05",
    name: "DBS Group Holdings Ltd",
    exchangeId: "sgx",
    countryCode: "SG",
    currency: "SGD",
    assetClass: "equity",
  },
  {
    symbol: "BHP",
    name: "BHP Group Limited",
    exchangeId: "asx",
    countryCode: "AU",
    currency: "AUD",
    assetClass: "equity",
  },
  {
    symbol: "PETR4",
    name: "Petroleo Brasileiro S.A. - Petrobras",
    exchangeId: "b3",
    countryCode: "BR",
    currency: "BRL",
    assetClass: "equity",
  },
  {
    symbol: "AMXL",
    name: "America Movil, S.A.B. de C.V.",
    exchangeId: "bmv",
    countryCode: "MX",
    currency: "MXN",
    assetClass: "equity",
  },
  {
    symbol: "NPN",
    name: "Naspers Limited",
    exchangeId: "jse",
    countryCode: "ZA",
    currency: "ZAR",
    assetClass: "equity",
  },
];